version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smk-sellerservice-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smk_sellerservice
    ports:
      - "5436:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - smk-sellerservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: smk-sellerservice-migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - smk-sellerservice-network
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/smk_sellerservice?sslmode=disable",
      "up"
    ]
    restart: on-failure

networks:
  smk-sellerservice-network:
    driver: bridge